In [2]:
import numpy as np
a1=np.array([1,2,3,4,5,6,7,8,9])
print(a1)
rsa=a1.reshape(3,3)
print(rsa)
print("accessing")
print(rsa[2] [1])
print(rsa[0,2])
print("all rows and 2nd col")
print(rsa[:,2])

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
accessing
8
3
all rows and 2nd col
[3 6 9]


In [4]:
print("modify")
rsa[2][1]=60
print(rsa)

modify
[[ 1  2  3]
 [ 4  5  6]
 [ 7 60  9]]


In [6]:
print("sum")
sum=np.sum(rsa)
print(sum)

sum
97


In [7]:
print("sum of col")
sum=np.sum(rsa,axis=0)
print(sum)

sum of col
[12 67 18]


In [8]:
print("sum of row")
sum=np.sum(rsa,axis=1)
print(sum)

sum of row
[ 6 15 76]


In [9]:
a=np.array([1,2,3])
print(a+2)
print(a*3)

[3 4 5]
[3 6 9]


In [10]:
a=[1,6,5]
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.max(a))
print(np.min(a))

12
4.0
5.0
6
1


In [11]:
arr1=np.array([1,2,3,4])
print(arr1)
arr2d=np.array([ [1,2],[3,4]])
print (arr2d)

[1 2 3 4]
[[1 2]
 [3 4]]


In [13]:
a1=np.array([1,2,3,4,5,6,7,8,9])
print(a1)
rsa=a1.reshape(3,3)
print(rsa)
print("accessing ")
print(rsa[2][1])   
print(rsa[0:2])
print("all row 2nd col")
print(rsa[:,2])
print("modify")
rsa[2][1]=60
print(rsa)
print("\n")
sum=np.sum(rsa)
print(sum)
print("sum of col")
sumc=np.sum(rsa,axis=0)
print(sumc)
print("sum of row")
sumr=np.sum(rsa,axis=1)
print(sumr)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
accessing 
8
[[1 2 3]
 [4 5 6]]
all row 2nd col
[3 6 9]
modify
[[ 1  2  3]
 [ 4  5  6]
 [ 7 60  9]]


97
sum of col
[12 67 18]
sum of row
[ 6 15 76]


In [14]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)
print(b.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
